### ISSUE TITLE
Проверка на стажировку

### ISSUE THREAD

**Issue by gabdr0** [wpcraft-ru/test#100]
Добрый день.
сайт: http://wordpressnotes.ru
код плагина: http://pastebin.com/NhbLqKDU
скрин шаблона: http://take.ms/9L2mq

**Comment by yumashev** [comment]
Картинок не хватает. Выглядит как не доделка.
В остальном ок.

**Comment by gabdr0** [comment]
Спасибо, вставил изображения.
http://wordpressnotes.ru

**Comment by yumashev** [comment]
Жопой чую шлак это.
Надо добавить 15 записей. С высокой вероятностью нет пагинации. Где то ошибка. Не понятного каким образом получилось так что на странице архива выводится идентификатор страницы. Это явное усложнение и не соблюдение кодекса. Все на много проще если правильно строить вывод постов.

**Comment by yumashev** [comment]
Правильно, список фильмов должен выводиться по адресу типа /films/
И при этом не должно быть добавлено лишних страниц.
Просто добавили тип поста и если в нем включен архив, то просто должен показываться список постов этого типа по заданному адресу.

Добавление страницы - это какой то явный костыль, который рано или поздно выходить боком и ломает систему.
