### ISSUE TITLE
Результаты работы над тестовым заданием

### ISSUE THREAD

**Issue by YushkinaS** [wpcraft-ru/test#101]
# test-task

Ссылка на сайт: http://php-yushkinas.rhcloud.com/

Ссылка на код плагина: https://github.com/YushkinaS/test-task/blob/master/film-post-type.php

Скриншоты: 
![single-films](https://github.com/YushkinaS/test-task/blob/master/%D1%81%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA3.png)
![Content-films часть 1](https://github.com/YushkinaS/test-task/blob/master/%D1%81%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA1.png)
![Content-films часть 2](https://github.com/YushkinaS/test-task/blob/master/%D1%81%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA2.png)
### Уточнить задание:
1. Должны ли поля “стоимость” и “дата выхода”  быть обязательными к заполнению?
2. Последние фильмы - по дате добавления на сайт или по дате выхода самого фильма? 
### По особенностям выполнения:
1. По пункту “На странице отдельного фильма данные выводим через создание и правку шаблона”
   Какой шаблон нужно было создавать? Ограничиться шаблоном single-films и вставить данные до или после контента? Или можно также создать Content-films? Мне кажется, лучше работать с шаблоном контента - больше вариантов размещения блоков.
2. Допустимо ли использовать ob_start() + ob_get_clean() (как у меня в плагине) для добавления данных к фильмам в списке? Или можно только строки склеивать?
### И по возникшим сложностям
1. Хотелось уменьшить картинку фильма (использовалась тема WPBSS). Но в лоб не получилось, т.к. там в стилях - для картинки min-width 100%. Поэтому картинки, на мой взгляд, очень большие для каталога фильмов. Как следует поступать в такой ситуации? Менять стили дочерней темы? А если хочется весь функционал, связанный с фильмами, положить в плагин - подключать в файле свой css, который перекроет стили темы? 
2. К слову о полном переносе работы с фильмами в плагин из темы - допустимо добавить в плагин свой файл шаблона Content-films?

Вдогонку еще один вопрос: 
такая обработка результатов get_posts() обязательна?

``` php
foreach( $myposts as $post ){ setup_postdata($post);
    ?>
    <li><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></li>
    <?php
}
wp_reset_postdata();
```

Можно не трогать setup_postdata? Ведь все нужные данные у нас есть в $post. Пример из кода выше у меня работает так:

``` php
foreach ( $posts as $post ) {
    ?>
    <li><a href="<?php echo get_permalink($post->ID); ?>"><?php echo $post->post_title; ?></a></li>
    <?php
}
```

**Comment by YushkinaS** [comment]
Вопрос по дополнительному заданию:
Выбрала задачу https://github.com/systemo-biz/casepress/issues/21
Ссылка на мой модуль: https://github.com/YushkinaS/test-task/blob/master/person_organization.php
Проблема: При сохранении персоны, если создается новая организация, то весь код после 
```php
$new_organization_id = wp_insert_post( $new_organization);
```
не выполняется, и не получается сохранить ID новой организации в метаполе. Сразу после нажатия кнопки "обновить" происходит переадресация на страницу новой организации. 
Я правильно понимаю, что это поведение прикреплено к одному из хуков сохранения поста и в данном случае его нужно отключить? 

Также интересно: зачем функции, прикрепленные к action 'save_post' возвращают $post_id?

**Comment by yumashev** [comment]
вывод данного "Страна", ссылка на страницу находится внутри тега иконки. Это нарушение логики Bootstrap в связи с чем шрифт изуродовался.

**Comment by YushkinaS** [comment]
обновлено

http://php-yushkinas.rhcloud.com/films/

![скриншот шаблона](https://github.com/YushkinaS/test-task/blob/master/%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%8B%20%D0%B8%20%D0%B6%D0%B0%D0%BD%D1%80%D0%B0.png)

**Comment by yumashev** [comment]
все ок.
давай уточним эл почту.

**Comment by YushkinaS** [comment]
svetlana.yushkina@gmail.com
