### ISSUE TITLE
Сделал задание прошу коммента

### ISSUE THREAD

**Issue by kazbeks** [wpcraft-ru/test#20]
http://nfb7701.bget.ru/movies/

**Comment by kazbeks** [comment]
все получилось!!! - http://nfb7701.bget.ru/movies/

**Comment by yumashev** [comment]
это максимум эстетики?

**Comment by kazbeks** [comment]
Что-то я не пойму что вам надо ?
16 янв. 2015 г. 15:54 пользователь "Anatoly Yumashev" <
notifications@github.com> написал:

**Comment by yumashev** [comment]
ну например то что между иконками и текстом нет пробелов. думаешь так хорошо? все нормально?

**Comment by kazbeks** [comment]
ok добавил пробелы
