### ISSUE TITLE
Проверьте задание пожалуйста! 

### ISSUE THREAD

**Issue by vlas86** [wpcraft-ru/test#29]
Добрый день! Проверьте пожалуйста задание, спасибо заранее. http://bestmovies.zz.mu/movies/

**Comment by vlas86** [comment]
Добрый день! Отправил результат выполнения, но не получил ответа. Возможно не правильно выполнил.

**Comment by yumashev** [comment]
Вывод терминов таксономии сделан не аккуратно. В идеале оформить их как лейблы и пробелы после запятой поставить.

**Comment by vlas86** [comment]
Я бы хотел вас поблагодарить, что даёте возможность и тратите своё время, чтобы обучить людей, это благое дело. Спасибо что проверили задание, исправил, возможно что то недопонял. Вот исправленный вариант http://bestmovies.zz.mu/movies/

**Comment by yumashev** [comment]
Это максимум возможной эстетики? )

**Comment by vlas86** [comment]
Можно чего сделать, если вопрос в оцентровке постера, или в таксономиях прошу подкорректировать, что именно не так? Если что то визуально не так или отображается не так на других устройствах, прошу подсказать над чем мне работать. Вот исправленный вариант с сеткой и постом http://bestmovies.zz.mu/movies/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%81%D1%82%D0%B5%D0%BB%D0%BB%D0%B0%D1%80/
я всё исправлю что нужно

**Comment by yumashev** [comment]
По правилам русского языка, после запятой нужен пробел.
Тут,же,получается,что,никаких,пробелов,нет.Это,разве,нормально?

**Comment by vlas86** [comment]
готово http://bestmovies.zz.mu/movies/

**Comment by yumashev** [comment]
ок, хватит походу )
можно еще попридераться, далеко от эстетики и общепринятых подходов, но думаю что пока хватит.
запиши тут почту, чтобы дальше уже в личке пообщаться

**Comment by vlas86** [comment]
vlas86@gmail.com

**Comment by vlas86** [comment]
я оставил почту, но никакого сообщения не было, напишите когда отправите, заранее спасибо!

**Comment by yumashev** [comment]
ага, заработался )
отправил
