### ISSUE TITLE
Вопросы, обсуждение

### ISSUE THREAD

**Issue by andreyradygin** [wpcraft-ru/test#3]
Здравствуйте!
Такое вот уточнение, я добавил два новых текстовых поля,  к типу записи -- post, соответственно эти два поля добавляются при добавлении и новой записи типа Фильмы, и дефолтной новой записи. Я так понимаю вы не случайно указали, что требуется, чтобы эти два поля были добавлены именно к Фильмам. Но в условиях отображения почему-то не удается найти конкретизацию по отображению по типам постов.
Т.е. я вижу условие "Запись", но там выпадающий список по уже существующим постам, а не их типу. Натолкните на верный путь - я неверно понял задание, или все же недосматриваю еще какой-то конфиг?

**Comment by acerus** [comment]
А обязательно на бесплатном хостинге делать? на своем сервере можно?

**Comment by yumashev** [comment]
@acerus можно
