### ISSUE TITLE
По поводу проверки задания

### ISSUE THREAD

**Issue by ghost** [wpcraft-ru/test#30]
Здравствуйте! 10 дней назад мне с email-а td@casepress.org прислали ссылку на тестовое задание. ч-з 2 дня я отправил назад на этот email результат - сделанный сайт, логин и пароль от админки, и логин/пароль от ftp с сайтом. Но никакого ответа назад не получил. Подскажите, что нужно сделать чтоб проверили мою работу, и что будет после проверки? Сам сайт вот - http://casepress-exerc.besaba.com

p,s, Всех с наступающим/наступившим Новым Годом :)

**Comment by yumashev** [comment]
Да, сделано хорошо!
Привет и с НГ )
Дай свою почту.

**Comment by altai90** [comment]
altai90@yandex.ru

**Comment by AAO2014** [comment]
Анатолий, а дальше что,  после теста?

**Comment by yumashev** [comment]
Ждем ответ на почту с уточняющими вопросами :)
