### ISSUE TITLE
Выполнено тестовое задание.

### ISSUE THREAD

**Issue by mrtwister** [wpcraft-ru/test#31]
Тестовое задание выполнил http://helloworld.zz.mu/movies/ Вопросов, не то, что не возникло, но все очень хорошо гуглилось, поэтому используя привычку "сначала загугли, потом спрашивай", к вашей помощи прибегать не пришлось. Вот вопросы которые возникали:
- Как добавить запись с типом "Фильм" - посмотрел другие "Issues" оказалось, эта проблема уже возникала и вордпресс, не понимает, кириллицы в названии категорий. 
- Почему по адресу http://helloworld.zz.mu/movies не отображается список сделанных записей, нашел ответ, в других "Issues", что не стоит галка, напротив свойства "архивный".
- Куда надо писать код, что бы вывести хук. Загуглил, нашел. Попробовал, вордпресс ответил ошибками времени исполнения, нашел код [здесь](https://github.com/systemo-biz/test/issues/25) посмотрел как работает, посмотрел другими глаза документацию. Скопипастил и немного подправил как мне надо код, заработало.
- Как вытащить нужные данные в список, что бы это было применимо, только к категории "Фильмы". Подумал немного, звать на помощь не пришлось.

> Сделайте вывод 4-х блоков данных в форме сетки 2х2 

 Непонятно, какие блоки, где вывести, на странице архива или на странице с записью. Посмотрел как сделано, у тех кто сдал, стало понятно, что речь идет о дополнительных полях. Сделал и там и там.

На этом вроде все. Постарался ничего не пропустить.

**Comment by yumashev** [comment]
Хорошая привычка :)
Почту в студию.

**Comment by mrtwister** [comment]
belyaev.rs@gmail.com
