### ISSUE TITLE
/

### ISSUE THREAD

**Issue by necinc** [wpcraft-ru/test#32]
Сама задача показывал уже достаточно давно, но отправили на доработку. Затем отправил законченный вариант, но возможно Вы не заметили, так как ответа не не было.
Вот ссылка:
http://taskmovies.zz.vc/movie/

Жду с нетерпением)

**Comment by yumashev** [comment]
Метки сделаны ляповато.
Нет пробелов. Нет упаковки в лейблы.
Покажи что ты можешь быть аккуратным :)
