### ISSUE TITLE
Выполнил тестовое задание

### ISSUE THREAD

**Issue by a10hello** [wpcraft-ru/test#33]
http://a10.zz.vc/movie
С проблемой сталкнулся когда не отображались записи по адресу /movie. Почитал документацию, покопался немного и сделал, с помощью того же плагина.
Оборажение таксонамии сделал, к счасть есть функции, не пришлось писать sql запросы.
Между делом изменил шрифт названия сайта.

**Comment by yumashev** [comment]
хорошая работа!
напиши свой email

**Comment by a10hello** [comment]
a10helloworld@gmail.com
