### ISSUE TITLE
Вроде выполнил задание

### ISSUE THREAD

**Issue by IgorVBelousov** [wpcraft-ru/test#34]
Ссылка http://test.belousovv.ru/. 

На счет хука, как я понял, нужно было сделать плагин. Вообще получилось дублирование кода в плагине и в файле темы.

Custom Post Type UI 1.0.5 - как я понял нужен для разработки, чтобы экспортнуть получившийся код в будущий плагин, или его принято использовать на конечном сайте.

Показ полей и таксономии делал по хелпу плагина Advanced Custom Fields. 

Послесловие: Дико был удивлен возможностью править код прямо из админки. Пропало предубеждение использования WordPress'а.

**Comment by yumashev** [comment]
отлично!
напиши свой email

**Comment by IgorVBelousov** [comment]
<igor@belousovv.ru>
