### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by Tommy88** [wpcraft-ru/test#38]
1. Использовал плагин custom-post-type-ui. Когда добавлял новые записи типа movies, то заметил, что они не отображаются на главной странице. Почему так происходит - не понятно. Самостоятельно было найдено решение путем вставки кода в файл index.php темы unite. А вот и сам код:
   <?php /\* Start the Loop */ query_posts(array('post_type' => array('post', 'movies')));?>
2. Создав меню, так и не смог увидеть в нем записей своей новой рубрики movies. Однако позже, в процессе ковыряния админки, установил плагин CPT Bootstrap Carousel, с помощью которого удалось добиться отображения своих записей. С появлением этого плагина в админке появилось дополнительно еще одно окно "Рубрика" для добавления в меню, которым я и воспользовался, а так же выбирал его при создании записей. На странице выбранного на сайте меню значилась надпись Archives. Почему?

Я следовал инструкциям в тесте, но ничего не получается. Два дня ковыряния админки конечно зря не прошли и интерес не пропал, но что же я делаю не так?

**Comment by Tommy88** [comment]
http://sha-red.hol.es/carousel_category/filmy/

**Comment by yumashev** [comment]
1. Они не должны отображаться на главной. Решение не верно в корне. Это костыль. Его надо убрать.
2. Плагин надо удалить.

Вопросы перезадать. Так чтобы они были понятны.

**Comment by Tommy88** [comment]
Почему фильмы не отображаются в моей рубрике?

**Comment by Tommy88** [comment]
http://sha-red.hol.es/
Проверьте, пожалуйста. Никаких костылей и аккуратно выглядит.

**Comment by Tommy88** [comment]
Не понятно, почему когда я создаю стандартные записи и добавляю их в меню через Рубрики, они отображаются в этом меню на сайте, а самостоятельно созданные типы записей - нет?

**Comment by yumashev** [comment]
Что значит меню? О чем речь? Выглядит нормально
