### ISSUE TITLE
Миссия выполнена!

### ISSUE THREAD

**Issue by Veliky** [wpcraft-ru/test#40]
Вот адрес моего творения)
http://systemo.zz.mu/

Сделал всё по инструкции, но заметил что в отличии от результатов остальных, у меня не отображаются таксономии в виде архивов. Так как в задании нет указания сделать архивы для таксономий, думаю что сделал что-то неправильно при их создании.

**Comment by yumashev** [comment]
добавил п. 4 в Требования. Надо добавиьт тут две ссылки.

**Comment by Veliky** [comment]
Код какого плагина требуется показать в п. 4.2?

**Comment by yumashev** [comment]
того что выводит данные о фильме через хук.
возможно у тебя он через тему сделан.
тогда можно код от туда сделать

**Comment by Veliky** [comment]
4.2 Код файла single.php: http://pastebin.com/r3avsyW0
4.3 Шаблон архива я практически не редактировал, так как реализовал через "content-movie", по-этому скриншоты этого файла добавил тоже.
http://systemo.zz.mu/screenshots/

**Comment by yumashev** [comment]
Не верно выполнено требование 2.2.
Надо переделать.
Сриншоты делают не так, читаем внимательней требование.

**Comment by Veliky** [comment]
2.2 именно через шаблон архива нужно сделать?
Можно по подробнее что не так со скриншотами?

**Comment by yumashev** [comment]
по 2.2. скопируй текст сюда, будем читать вместе.

по скриншоту скопируй текст сюда, будем читать вместе.

**Comment by Veliky** [comment]
По 2.2 уже дошло, перепутал с 2.1, извиняюсь за невнимательность.
Скриншоты:
сделайте снимок экрана с кодом шаблона архива фильмов - сделал
(если своего нет, то рекомендуем monosnap.com) - сделал снимки через monosnap, потом залил их на ихнее хранилище. Не нашёл способа показать папки с хранилища, и подумал что лучше залить на хостинг.

**Comment by yumashev** [comment]
Надо найти. Это вот так выглядит в итоге http://monosnap.com/image/BOhYOSnQl3qDh3J6P5ec8cKDvHtn2a

Там кнопка Загрузить сверху справа

**Comment by Veliky** [comment]
В том и суть, что как давать ссылку на картинку я понял сразу. Но ведь код длинный, и в один файл не вмещается, по-этому скриншотов получилось несколько. Из-за этого решил демонстрировать их папками, а этот самый monosnap демонстрировать папками не даёт.

**Comment by yumashev** [comment]
сделай сколько влезет

**Comment by Veliky** [comment]
Написал плагин. Ссылка на код: http://pastebin.com/1cFauiJV

Скриншоты файла archive-movie:
http://take.ms/tdAXo
http://take.ms/lc1Qd
http://take.ms/esoKn

Скриншоты файла content-movie:
http://take.ms/2iw4n
http://take.ms/FogRI
http://take.ms/LJgYx

**Comment by yumashev** [comment]
Хорошо. Запиши тут email.

**Comment by Veliky** [comment]
veliky.web@gmail.com
