### ISSUE TITLE
Проверка тестового задания

### ISSUE THREAD

**Issue by L3n1n** [wpcraft-ru/test#41]
Выполнил тестовое задание – http://allmoviesbeta.16mb.com/movies/

Для задания использовал плагины ACF и CPT UI – при создании нового типа записей дополнительно использовал миниатюры и таксономию "Актеры", о которой было лишь поверхностное упоминание в тексте задания.

На счет второго пункта я не совсем уверен, что выполнил его так, как было нужно, а именно: я использовал шаблон записи single-movies.php в дочерней теме вместо хука. Так же в данном пункте я решил вывести миниатюры записей и добавил вывод всей таксономии и дополнительных полей на странице записи фильмов.

С Bootstrap ранее не был знаком, но проблем не возникло после прочтения документации и небольшого поиска.

**Comment by yumashev** [comment]
>> На счет второго пункта я не совсем уверен, что выполнил его так, как было нужно, а именно: я использовал шаблон записи single-movies.php в дочерней теме вместо хука.

Это правильно вообще. Но не тут.
Тут была задача сделать через хук. Цель - убедиться что вы усвоили логику работы хуков.
Потому надо переделать.
И еще добавил раздел 4. Его тоже надо будет сделать.

**Comment by L3n1n** [comment]
Сделал через хук. И в связи с недавним обновлением текста задания заметил пункт 2.4, который так же решил сделать.

Страница с шорткодом – http://allmoviesbeta.16mb.com/shortkod/
Код плагина – http://pastebin.com/d24JvtLE
Скриншот шаблона архива – http://i.imgur.com/1pbUmVO.jpg

**Comment by yumashev** [comment]
Хорошая работа!
Нужно тут свой email записать

**Comment by L3n1n** [comment]
Спасибо. Моя электронная почта: utipusichka@gmail.com
