### ISSUE TITLE
Тестовое задание на проверку

### ISSUE THREAD

**Issue by inwebus** [wpcraft-ru/test#42]
Вот мое задание на проверку:

1) Рабочий сайт http://inwebus.esy.es/
2) Код плагина http://pastebin.com/FUafb0sC
3) Скриншот с кодом шаблона архива фильмов http://prntscr.com/6ubxpq

**Comment by yumashev** [comment]
п 2 - надо весь код, от начала до конца

**Comment by yumashev** [comment]
в п 3 не увидел ветки где сделан вывод данных.
или он сделан в шаблоне контента?

**Comment by inwebus** [comment]
В плагине сделан

**Comment by yumashev** [comment]
Это нарушение требование №2.3.
Нужно исправить.

**Comment by inwebus** [comment]
2) Поправил код плагина http://pastebin.com/FUafb0sC
3) Архивная страница http://prntscr.com/6uc0z3

Добавил шаблон content-movie.php в дочернюю тему. Теперь так? Или надо было именно в archive-movie.php реализовать вывод информации?

**Comment by yumashev** [comment]
в п 2 хтмл дерево читается крайне плохо.
так лучше не писать. мелкие куски еще куда не шло в 2-3 строки, а крупные лучше в хтмл писать.
через ob_start http://wpcraft.ru/vy-vod-html-echo-i-shablonov-cherez-shortkod-v-wordpress/

**Comment by yumashev** [comment]
по п 3 все ок.
читаемость кода поправь и можно тут мыло указать, для дальнейшего общения.

**Comment by inwebus** [comment]
Сделал через ob_start http://pastebin.com/FUafb0sC. 

E-mail inwebus@gmail.com
