### ISSUE TITLE
произвольные поля

### ISSUE THREAD

**Issue by Alexey666** [wpcraft-ru/test#43]
1

**Comment by yumashev** [comment]
п. 4 теста прочитай, там есть задание на проверку знаний того как надо показывать код и задавать вопросы.

**Comment by Alexey666** [comment]
http://pastebin.com/39EzjAsC#
Суть вопроса как вывести стоимость и дату выхода. Какой код использовать?) у меня не подхватывает произвольные поля! то ли не те функции юзаю то ли не указано конкретно что нужно отображать. Если подскажите будет не плохо! еще дополнительно что посоветуете почитать для общего развития по php (материалов много, хочется доступно достойный)
Заранее благодарен!
P.S.   я еще буду спрашивать про хуки, упаковку и т.п. наберитесь терпения пожалуйста.

**Comment by yumashev** [comment]
сложно сказать, я так код писать не умею.

вот так работаем когда надо html через вернуть в функции http://wpcraft.ru/vy-vod-html-echo-i-shablonov-cherez-shortkod-v-wordpress/

перепиши, мб чего понятней станет

**Comment by Alexey666** [comment]
Все привет! Я не сдался я еще воюю!) разобрался с отображением произвольных полей (помогло руководство встроенное в плагин) делал все через редактирование functions.php и постоянным обновлением по фтп после изменений!) так что когда выскакивали косяки легко было поменять все в лучшую сторону! Итак функция называется the_field() . Далее при попытке отобразить все на главной шорткодом добился того, что рендомно появляется один из 5 фильмов ! Результат не удовлетворил, работаю дальше!
Анатолий подскажите пожалуйста. Что происходит с людьми у которых вы попросили email? (Пропадают люди куда-то с чата!)))))

**Comment by yumashev** [comment]
Мы их похищаем через email и забираем в атлантиду.
Давай по делу вопросы. Я чуть в мыле, ценю чувство юмора и наблюдательность, но ввиду дефицита ресурсов, могу заигнорить.

**Comment by Alexey666** [comment]
http://ruskino24.hol.es

**Comment by yumashev** [comment]
сайт не работает

**Comment by Alexey666** [comment]
Попробуйте еще раз!) может на хостинге какие работы были! 
Если Вас устроит такое выполнение работы внешне, то сразу отпралю код!

**Comment by yumashev** [comment]
Неа не устроит. И можно закрывать вопрос.
Нет смысла продолжать по ряду причин:
1. Ты не понял задание
2. Сделал не то что нужно
3. Сделал кучу лишнего - нарушив принцип бритвы Оккама
4. Вместо ваты добавил лажу

Это означает что если дать тебе задание то получим тоже самое:
1. Ты не поймешь его, а если поймешь то не так
2. Сделаешь не то что нужно
3. Сделаешь кучу лишнего

Мы потеряем время, деньги, репутацию и клиента.
Ты ничего не заработаешь.
Все окажутся в проигрыше.

Потому продолжать нет смысла.

**Comment by Alexey666** [comment]
Прям цугцванг какой-то!) Благодарен сервису за возможность узнать что то новое! (самостоятельно) 
P.S. напоминаю!) я здесь не из за возможности заработать был!) хобби у меня такое!
Свое мнение Вам писать не буду! не поймете!
