### ISSUE TITLE
Прошу проверить задание

### ISSUE THREAD

**Issue by Asche98** [wpcraft-ru/test#45]
Здравствуйте, у меня всё готово:
1. http://worldoffilms.16mb.com/
2. http://pastebin.com/bCv3vsCz
3. http://images.vfl.ru/ii/1429727437/e0c5c357/8518789.png

**Comment by yumashev** [comment]
Напиши тут свою почту. Переходим к след этапу )

**Comment by Asche98** [comment]
super-elena11@mail.ru
