### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by RoberGRM** [wpcraft-ru/test#46]
Добрый день. Высылаю Вам результаты тестового задание:
1. сайт: http://videomania.zz.mu
2. ссылку на код плагина: http://pastebin.com/Qz2J88z8
3. скриншот: http://take.ms/kYoU3

**Comment by RoberGRM** [comment]
Сетку сделал только на странице отдельного фильма. В списке фильмов не очень будит смотреться. Я Bootstrap как то обходил стороной, теперь вмести с Гуглом осваиваем.

**Comment by yumashev** [comment]
Зачем в style css добавлен класс .clear?

**Comment by yumashev** [comment]
Функция movie_info() - состоит из говнокода который довольно тяжело читать.
Ты умеешь писать читаемый код с нормальным DOM деревом? Или весь код будет из такой лапши состоять?

**Comment by yumashev** [comment]
Кодга пишешь HTML конструкции более 5-7 строк, то надо php писать внутри HTML, чтобы читалось как нормальное DOM дерево. А ты HTML внутри php пишешь. И это полная лажа, читать и разбираться потом в таком говнокоде врагу не пожелаешь.

**Comment by RoberGRM** [comment]
:) час исправлю. А класс clear использовал что бы исключить обтекание.

**Comment by yumashev** [comment]
Вопрос в том что такой класс уже есть в BS http://getbootstrap.com/css/#helper-classes-clearfix

И зачем усложнять код дубляжом того что уже есть?

Это маленькая задача, тут сложно допустить усложнение. Но удалось. А что будет с большими задачами? В малых задачах умение не усложнять и не плодить лишние сущности крайне критично. Нужно уметь использовать то что есть и не выдумывать изобретение велосипедов.

Вопрос, умеешь ли ты так работать? Или нам придется каждый раз вычищать твой код от кучи лишних сущностей?

**Comment by yumashev** [comment]
В остальном сделано на твердую 4. Надо тут почту записать, чтобы к след этапу перейти.

**Comment by RoberGRM** [comment]
Ок. сейчас я исправлю функцию и вёрстку. grm7731@mail.ru

**Comment by RoberGRM** [comment]
Разобраться с архивной страницей не могу. Почему то выборки по году издание не происходит.
Код архивного файла: http://pastebin.com/Lyjc5nBP
Сайт тот же самый. Плагин изменил.

**Comment by RoberGRM** [comment]
С годом разобрался исправил :)
