### ISSUE TITLE
Результат выполнения тестового задания

### ISSUE THREAD

**Issue by makaravich** [wpcraft-ru/test#47]
В ходе выполнения тестового задания появился, пожалуй, только один серьезный вопрос: никак не получается вставлять шорткоды в текст поста. Где-то в интернете прочитал, что не все шаблоны это позволяют. В качестве универсального решения использовал код: echo do_shortcode('[get_last_movie]'), то есть вставлял непосредственно в РНР-файл, а не в текст поста. 
Будете ли вы это считать недочетом? 
Есть ли какие-либо более изящные решения этой проблемы?

Ну а если этот момент не критичен, то тогда отдаю задание на проверку:
1.  Ссылка на рабочий сайт: http://makaravich.esy.es/
2.  Ссылка на код плагина: http://pastebin.com/j9MAZMtE 
3.  Ссылка на скриншот с кодом шаблона архива: https://www.dropbox.com/s/glju1bd7e0ga2cg/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-24%2015.16.40.png?dl=0

**Comment by yumashev** [comment]
Пукнт 3 сделан не верно. Переделать по ТЗ.

**Comment by yumashev** [comment]
Каталог фильмов тоже сделан не верно. Как пост типа запись, а надо как пост типа Фильм.

**Comment by makaravich** [comment]
Насчет пункта 3 переделал. Вот ссылка: http://take.ms/sbxdF
Насчет каталога не согласен: в ТЗ написано: "Нужно создать шаблон архива типа записи в дочерней теме". Или я что-то неправильно понял?

**Comment by makaravich** [comment]
Насчет пункта 3 переделал. Вот ссылка: http://take.ms/sbxdF
Насчет каталога не согласен: в ТЗ написано: "Нужно создать шаблон архива типа записи в дочерней теме". Или я что-то неправильно понял?

**Comment by makaravich** [comment]
Вы как-нибудь прокомментируете мое предыдущее сообщение? )

**Comment by yumashev** [comment]
Шаблон архива типа записи Фильмы.
Вы же сделали рубрику Фильмы и храните их как обычный тип записи Пост.
В корне не верное решение.
Есть сомнение в целессобразности продолжения теста. При условии что задание не понято. Инструкции не читаны. Сделано не то что нужно. Вопросы не заданы.
Это очень простая задача.
Что будет если нужно будет решить среднюю или сложную задачу?
При таком подходе шансы на успех крайне малы.
