### ISSUE TITLE
Тестовое задание на проверку!

### ISSUE THREAD

**Issue by Burick** [wpcraft-ru/test#49]
Собственно тестовый сайт на проверку - http://burick.96.lt
На странице отдельного фильма например на этой  - http://burick.96.lt/movie/ночной-беглец/  информация о цене сеанса,  времени выхода в прокат, стране и жанре фильма выводится через плагин http://pastebin.com/raM8kMUU 
Для создания страницы архива фильмов - http://burick.96.lt/?post_type=movie, создан шаблон архива типа поста **movie** путем копирования **archive.php** из родительской темы, переименование в **archive-movie.php**  и небольшое редактирование - [archive-movie.php](https://nimbus.everhelper.me/client/notes/share/204641/CJNhPEiwI2u9tWAA4270cBT244LmPd0U) , таким же образом был создан в дочерней теме шаблон **content-movie.php**  и функция **get_film_info()** в файле **functions.php** 
На главной странице выведено 5 последних фильмов при помощи созданного шорткода в файле  **functions.php**
Сетку и оформление  label + иконки можно увидеть на странице http://burick.96.lt/?post_type=movie
Остались некоторые непонятные моменты..
К примеру, страница с шорткодом отлично выводится на главной, если ее поставить отдельно в менюшку то говорит "OOOPS!!" - http://burick.96.lt/new-copy/,почему  http://burick.96.lt/about , к примеру, работает... опять же с ней не разобрался почему левый сайдбар выводится, если она на главной, только с помощью виджетов и то для правильного отображения придется переверстать шаблон... 
Почему не работаю ссылки таксономий типа http://burick.96.lt/genre/%d0%ba%d0%be%d0%bc%d0%b5%d0%b4%d0%b8%d1%8f/ и http://burick.96.lt/genre/

**Comment by burick** [comment]
Хм.. В общем я запутался.в менюшку выкинул и страницу и запись - ничо не работает(( только фильмы, наверное что то с шаблоном начудил

**Comment by yumashev** [comment]
404 ошиба при подключении стилей родительской темы. Доска сделана не правильно. От сюда косой вид всего сайта.

Перечитай еще раз ТЗ и все инструкции подсказки. Сделай по новой. Покажи что то хоть как то работающее.

**Comment by burick** [comment]
Да, я переделал все, сейчас загрузил, настраиваю, потому ошибки, когда сделаю отпишусь

**Comment by burick** [comment]
![2015-05-02_193747](https://cloud.githubusercontent.com/assets/4094310/7441896/686557b8-f104-11e4-9737-40ed39bd5b1a.jpg)
[Тестовый сайт](http://burick.96.lt/)
[Плагин](http://pastebin.com/1cSp5UWE)

Есть трабла, не выводятся страницы, скорей всего что то в настройках WordPress, на локалке работает все норм

**Comment by burick** [comment]
Поставил ЧПУ по умолчанию баг исчез..
