### ISSUE TITLE
Проверьте задание

### ISSUE THREAD

**Issue by Cepera72** [wpcraft-ru/test#50]
Возникло много проблем и вопросов, так как первый раз занимался подобным делом, задание выполнено по минимуму возможно с недочетами.
Спасибо моим друзьям Google и еше одному человеку, которые постоянно тыкали меня носом в косяки и снабжали литературой))
4.1. http://trevor.hol.es/
4.2. плагин: http://pastebin.com/Yg54uRKE
4.3. архив http://take.ms/N0Gdy

**Comment by yumashev** [comment]
Зря тыкал. Артем кончено молодец, но такая помощь на самом деле может выйти боком.
Он же не будет все время тебе помогать. А это простая задача.
Пойдут сложные и что? Завалишься, он не поможет, денег не заработаешь, клиент уйдет, репутацияю подорвешь нашу. Все будут в убытках.
Лучше самому все делать. Так будет понятно потянешь или нет.
Сейчас это означает огромный риск. Но будем пробовать.
