### ISSUE TITLE
Тестовое задание на проверку.

### ISSUE THREAD

**Issue by Nimteya** [wpcraft-ru/test#54]
Добрый день!

Выкладываю на проверку свою работу:

Адрес сайта: http://cinematic.zz.mu/
Код плагина: http://pastebin.com/Vw9t9Txc
Снимки экрана с кодом шаблона архива фильмов:
- выборка и старт цикла http://take.ms/0BA2V
- вывод доп. инфы.      http://take.ms/xQsPH

**Comment by yumashev** [comment]
картинок нет
