### ISSUE TITLE
Стоимость сеанса и Дата выхода - действительно текстовые?

### ISSUE THREAD

**Issue by Malemute** [wpcraft-ru/test#56]
Всем привет. Правильно ли я понимаю, что в задании фразу "добавить текстовые поля Стоимость сеанса и Дата выхода в прокат" не стоит понимать буквально? Там просится не текст, а дата (скажем, Date Picker - http://www.advancedcustomfields.com/resources/date-picker/ ) и число.

**Comment by yumashev** [comment]
Можешь понимать как угодно.
Внешний вид может быть любой, но хранятся данные все равно текстом.
Датапикеры, колорпикеры или любые другие модификторы инпутов лишь меняют интерфейс пользователя. Но сохраняется это все равно текстом в метаполя.
