### ISSUE TITLE
Заковырялась не там где следовало бы(...

### ISSUE THREAD

**Issue by hvs-fasya** [wpcraft-ru/test#58]
С Wordrpess'ом продвигаюсь по тестовому заданию более менее... все засады с Openshift - понимаю, что не очень по делу и можно наплевать, но мы же вроде как учимся....
Вопросы:
1.правильно я понимаю, что лазать на на этот сервер можно только через git или ssh (не было других  забот - пришлось быстренько азы осваивать)...
2. какое-то обезьянничание при push с локалки - надо все плагины и темы откопировать в папку .openschift и только тогда сервер всё это кушает с git'а... может я чего-то недопоняла? а то чувствую себя немного неумной всё по пять раз перезаписывать...
3. то же самое с push новых типов записей, таксономий и кастомных полей - git считает, что все, что касается БД всобачиванию на сервер не подлежит... вроде нашла как эту всю панаму импортировать, но как-то хлопотно это все...

можно, наверное, сразу всё на сервере в админке делать, но мне показалось это неприличным... если скажете, что надо на всё это начхать, так и поступим)..

**Comment by yumashev** [comment]
с OpenShift это круто ) обычно выбирают hostinger.
Там можно через sftp работу вести. А можно через GIT. Но с небольшим ударом в бубен.
Лучше SFTP.
Еще лучше Хостингер. ОпенШифт это для гурманов и экстрималов.

**Comment by hvs-fasya** [comment]
дык кто ж знал то, я ж только вчера это всё первый раз в жизни и увидала )))) предупреждать надо - теперь я еще три дня буду доковыривать раз уж начала)... а с базой то как там работать? как туда дамп подсунуть? - не могу найти... или плюнуть и пока всё в админке делать?


Среда, 24 июня 2015, 1:22 -07:00 от Anatoly Yumashev <notifications@github.com>:

**Comment by yumashev** [comment]
не стоит. если нет 5 лет опыта ковыряния сложных приложений, то ты тут забуксуешь на вечно.
потому лучше начни с Хостингера. он полегче и попроще в раз 100

**Comment by hvs-fasya** [comment]
ааааа) целый день псу под хвост, но я далеко продвинулась, если чо)))))))... с учетом того, что я только полгода назад про то, что html в природе существует, узнала - лучше начнем эту жвачку заново пережевывать, не привыкать....


Среда, 24 июня 2015, 1:29 -07:00 от Anatoly Yumashev <notifications@github.com>:

**Comment by hvs-fasya** [comment]
Сразу еще вопрос:
залезла сейчас в MySQL - а там, мама дорогая, в таблице wp_term_taxonomy 8 штук моих таксономий 'actor' и парочка 'genre'... в админке - все вроде бы прилично... это как же так вышло... понятно, что я несколько раз редактировала каждую, но редактировала же - не создавала... и куда их теперь девать....


Среда, 24 июня 2015, 1:29 -07:00 от Anatoly Yumashev <notifications@github.com>:

**Comment by yumashev** [comment]
Для решения этой задачи не надо лазить в MySQL. Там много чего страшного и не понятного может быть. Но все заморочки берет на себя WordPress.

**Comment by hvs-fasya** [comment]
интересно же чего не слазать то посмотреть одним глазком... ответ нашла в help CPT UI - нечего было сто раз менять slug от этих taxonomy, новый slug - новая запись, ненужные можно удалять

**Comment by hvs-fasya** [comment]
Сайт:                          http://hvsmovies.hol.es/all-movies
Код плагина:              http://pastebin.com/xerGA721
Снапшот шаблона:    http://take.ms/SuEYf

Недоработки есть... про которые знаю сама - буду доделывать, про которые напишете - буду рассматривать....
 п. 5.3. буду разглядывать уже завтра
