### ISSUE TITLE
Посмотрите результаты, пожалуйста.

### ISSUE THREAD

**Issue by hvs-fasya** [wpcraft-ru/test#59]
issue #58 - внутри ссылки на результаты тестового задания. Посмотрите пожалуйста.

**Comment by yumashev** [comment]
как закончишь тут напиши

**Comment by hvs-fasya** [comment]
Помогайте, пожалуйста... в casepress/issues issue #21 "Добавить метабокс Организации в Персоны"  уперлась в безобразное поведение Select2...

1. select2  в режиме multiple с тегами <select> работать ну совсем не желает, только с <input>, хотя версия select2 вроде бы свежая... соответственно, не могу задать preselected опции таким макаром как они предлагают в доках - просто через указании нужных <option>
все examples у них в доках только с <select>, а про <input> гордо пишут, что отныне с новой версией с <input>ами можно не мараться...

2. c ajax внутри select2 фигня какая-то:

http://pastebin.com/8CU6knqc - код
http://take.ms/TAZsa - снимок экрана
http://take.ms/c02gJ - снимок экрана

получаю данные отдельным аяксом снаружи и скармливаю в select2 - работает,
то же самое пихаю внутрь select2 как опцию ajax - тишина и покой((( в коде закомментирован один из полсотни вариантов моего  ajax - 
2а. опции select2:
    data: если я правильно понимаю это данные, которые мы передаем из формы, а я пока что ничего не передаю - только получаю... убираю опцию data - ничего не работает, добавляю тупым копипастом "лишь бы было" ajax работает криво - старательно ищет и "nothing found"
   results: это у них кто???? те опции селекта, которые мы увидим???? и как с ними обращаться до того, как мы их подали на экран???

если можно, пропишите, в каком порядке чего в нашем случае в select2 срабатывает и какая опция селекта при этом подключается к процессу...

**Comment by hvs-fasya** [comment]
Читать здесь...
Исправила очепятки...

Помогайте, пожалуйста... в casepress/issues issue #21 "Добавить метабокс Организации в Персоны" уперлась в безобразное поведение Select2...

    select2 в режиме multiple с тегами select работать ну совсем не желает, только с input, хотя версия select2 вроде бы свежая... соответственно, не могу задать preselected опции таким макаром как они предлагают в доках - просто через указании нужных option
    все examples у них в доках только с select, а про input гордо пишут, что отныне с новой версией с inputами можно не мараться...

    c ajax внутри select2 фигня какая-то:

http://pastebin.com/8CU6knqc - код
http://take.ms/TAZsa - снимок экрана
http://take.ms/c02gJ - снимок экрана

получаю данные отдельным аяксом снаружи и скармливаю в select2 - работает,
то же самое пихаю внутрь select2 как опцию ajax - тишина и покой((( в коде закомментирован один из полсотни вариантов моего ajax -
2а. опции select2:
data: если я правильно понимаю это данные, которые мы передаем из формы, а я пока что ничего не передаю - только получаю... убираю опцию data - ничего не работает, добавляю тупым копипастом "лишь бы было" ajax работает криво - старательно ищет и "nothing found"
results: это у них кто???? те опции селекта, которые мы увидим???? и как с ними обращаться до того, как мы их подали на экран???

если можно, пропишите, в каком порядке чего в нашем случае в select2 срабатывает и какая опция селекта при этом подключается к процессу...

**Comment by hvs-fasya** [comment]
Да что ж такое - этот редактор какой-то шибко умный(((( пробуем отправить читабельно еще разок....

Помогайте, пожалуйста... в casepress/issues issue #21 "Добавить метабокс Организации в Персоны" уперлась в безобразное поведение Select2...

select2 в режиме multiple с тегами select работать ну совсем не желает, только с input, хотя версия select2 вроде бы свежая... соответственно, не могу задать preselected опции таким макаром как они предлагают в доках - просто через указании нужных option
 все examples у них в доках только с select, а про input гордо пишут, что отныне с новой версией с ами можно не мараться...

 c ajax внутри select2 фигня какая-то:

http://pastebin.com/8CU6knqc - код
http://take.ms/TAZsa - снимок экрана
http://take.ms/c02gJ - снимок экрана

получаю данные отдельным аяксом снаружи и скармливаю в select2 - работает,
то же самое пихаю внутрь select2 как опцию ajax - тишина и покой((( в коде закомментирован один из полсотни вариантов моего ajax -
2а. опции select2:
data: если я правильно понимаю это данные, которые мы передаем из формы, а я пока что ничего не передаю - только получаю... убираю опцию data - ничего не работает, добавляю тупым копипастом "лишь бы было" ajax работает криво - старательно ищет и "nothing found"

results: это у них кто???? те опции селекта, которые мы увидим???? и как с ними обращаться до того, как мы их подали на экран???

если можно, пропишите, в каком порядке чего в нашем случае в select2 срабатывает и какая опция селекта при этом подключается к процессу...

**Comment by yumashev** [comment]
Нифига себе куда тебя понесло :) Не сама простая задачка выбрана. Но столь смелый шаг зачтется ))

Сами вопросы о том как решать эту задачу лучше там и задавать https://github.com/systemo-biz/casepress/issues/21

 echo json_encode($org_array); лучше заменить на специальную функцию http://wp-kama.ru/function/wp_send_json

пример https://github.com/systemo-biz/casepress-objects/blob/master/inc/meta.php#L44

конструкция $html .= '  <link href= - это ужас.

тут можно использовать просто html. см пример https://github.com/systemo-biz/casepress-objects/blob/master/inc/meta.php#L82

поправь это. код будет лучше читаться и от туда уже смогу помочь.

продолжать обсуждение этой задачу еще раз повторю лучше тут https://github.com/systemo-biz/casepress/issues/21 - чтобы не терять нить решения.

**Comment by yumashev** [comment]
кстати пример рабочего метабокса и очень похожего написан тут https://github.com/systemo-biz/casepress-objects/blob/master/inc/meta.php

можно его взять за основу. скопипастить и получится почти рабочее решение. чуть правок и готово.

сам плагин можно поставить и посмотреть как он работает. добавить объект и ответственного. будет понятно.

**Comment by hvs-fasya** [comment]
wp_send_json - зараза - мнит себя целым wp_die() и сразу прекращает дальнейшее исполнение всего wordpress на напрочь... по крайней в единый php файл оно у меня лезть не пожелало... но это, ладно, подробности.... а в ветку для приличных людей я лезть с вопросами постеснялась, пока мой уродец-инвалидка еле дышит и не шаволится толком... если справлюсь, чтоб оно как-то работало и там хоть что-то можно было разобрать, отпишусь туда...
