### ISSUE TITLE
Вопрос по пункту 1.6.

### ISSUE THREAD

**Issue by coller13** [wpcraft-ru/test#73]
"Добавляем 2 текстовых поля к типу поста Фильмы: Стоимость сеанса и Дата выхода в прокат. "

Нужно просто добавить два Custom Field? Или именно добавить два произвольных текстовых поля только ко всем постам (в т.ч. новым добавляемым) рубрики "Фильмы"?

**Comment by yumashev** [comment]
Сказано что для типа поста. От куда взялось понятие рубрики?

**Comment by coller13** [comment]
Рубрика - это вроде как локализованное понятие таксономии "Фильмы".
С плагином ACF сделать просто — там кроме типа поста можно указать таксономию, для которой использовать добавленные поля.
Просто задумался над реализацией этого, чтобы попробовать обойтись без плагина.

**Comment by yumashev** [comment]
Да, можно. Но без плагина такое реализовать будет не просто.
Там это делается через яваскрипты и AJAX, только в ACF.
Самому такое можно написать только если очень хорошо знать скрипты и аякс

**Comment by gorodsb** [comment]
А если сделать поле "Дата выхода в прокат" не текстовым, а выбором даты из календаря? Должно быть удобнее.
