### ISSUE TITLE
отчёт

### ISSUE THREAD

**Issue by ghost** [wpcraft-ru/test#74]
http://r3ewrersd3.esy.es/ - ссылка на тестовый сайт. (На hostinger; не всегда доступен.)

http://pastebin.com/eGPtZTK2 - код плагина (последняя версия, 27.10.2015 14:35 МСК).
http://pastebin.com/f6AKUN8Y - код шаблона страницы фильма (последняя версия, 27.10.2015 14:35 МСК)

http://rghost.net/8MKKW6x7k - снимок экрана с кодом шаблона страницы фильма (старая версия).
И один пункт из https://github.com/systemo-biz/casepress/issues/29 сделал.

**Comment by yumashev** [comment]
ок, напиши тут свой email, продолжим в почте

**Comment by yumashev** [comment]
хотя не.
не вижу списка фильмов в целом

**Comment by fw72** [comment]
Обновил страницу по ссылке на каталог (полный список фильмов с выводом данных через хук).

А список из последних добавленных 5 фильмов перенёс на др. страницу.

(И то, и то есть в меню.)

Отладочные данные специально не убирал.

Выяснил, что внутри плагина из переменной "$post" ничего не берётся, и нужно использовать только "get...".

**Comment by fw72** [comment]
Обновил страницу по ссылке на каталог (теперь там полный список фильмов с выводом данных через хук).

А список из последних добавленных 5 фильмов (через shortcode) перенёс на др. страницу.

Отладочные данные специально не убирал.

Выяснил, что внутри плагина из переменной "$post" ничего не берётся, и нужно использовать только "get...".

**Comment by fw72** [comment]
Обновил страницу по ссылке на каталог (теперь там полный список фильмов с выводом данных через хук).

А список из последних добавленных 5 фильмов (через shortcode) перенёс на др. страницу.

Вывод отладочных данные специально оставил.

Выяснил, что внутри плагина из переменной "$post" ничего не берётся, и нужно использовать только "get...".
![capture_20151024_131414 - template films list](https://cloud.githubusercontent.com/assets/14884249/10709696/bbb68e10-7a51-11e5-959d-b7ebf6ade601.png)
![capture_20151024_131555 - plugin new version](https://cloud.githubusercontent.com/assets/14884249/10709697/bbb99d94-7a51-11e5-9ccf-8a9d1cd51601.png)

**Comment by fw72** [comment]
ivanov.systemo.biz@yandex.ru

**Comment by yumashev** [comment]
не нашел такой почты в заявках на стажировку

**Comment by fw72** [comment]
Вышеуказанный ящик завёл специально для SB.

А заявку подавал с forwork72@yandex.ru .

**Comment by fw72** [comment]
Готово.

Заодно нашёл косяк - открытие нового div вместо закрытия старого, из-за которого всё ехало (особенно это было заметно при выводе списка фильмов).

Ссылки на код приёл в самом верхнем сообщении.

**Comment by yumashev** [comment]
1. я так и не понял как выводится список фильмов, но точно с ошибкой
2. вот это кошмар http://pastebin.com/f6AKUN8Y - нужно перечитать принципы построения страниц. Не может быть функций внутри шаблонов.

все плохо, так писать код нельзя.

**Comment by fw72** [comment]
1. Ошибка в чём? Проверил соответствие выводимых данных в списке и на единичных страницах - всё совпадает. Если про организацию цикла, то на wpkama.ru написано, что query_posts() без особой надобности не надо использовать. Я сделал через WP_query().

2. http://pastebin.com/MbEUmjQT - обновлённый шаблон страницы единичного фильма.
Изначально у меня было без функций, но смущало то, что дополнительные данные выводились либо выше, чем нужно, либо ниже. Сейчас расположение сделал, как было до публикации отчёта, но при этом чтоб была возможность комментирования и добавления в избранное, нужно в single-film.php покопировать соотв. части из content-single.php (род. темы). Я правильно понимаю?

**Comment by yumashev** [comment]
1. в том что вообще не надо никаких циклов. эта логика работает без создания шаблонов. просто вводишь слаг типа поста и он выводит список фильмов. вот с этим и надо работать. не городя костыли.
2. get_post_field('post_content - это плохо. есть функция the_content. зачем ты ее удалили и усложнил?
3. постарйся избавиться от лишних echo. они тут никчему. это шаблон. с ними код читаетя жутко тяжело. использование echo допустимо там где без него никак.
