### ISSUE TITLE
Проверить работу

### ISSUE THREAD

**Issue by PrudnikovMihail** [wpcraft-ru/test#75]
Написал плагин, но при активации выдает такое сообщение:

Плагин произвёл при активации 7 символов неожиданного вывода. Если вы заметите ошибку «headers already sent», проблемы с RSS-лентами или другие неполадки, попробуйте деактивировать или удалить этот плагин.

Плагин работает, как надо, но хотелось бы понять  в чем ошибка.

И еще вместо плагина Custom Post Type Maker я использую Types - это не будет ошибкой.

**Comment by PrudnikovMihail** [comment]
Нашел проблему почему появлялась ошибка:

Плагин произвел при активации 7 символов неожиданного вывода. Если вы заметите ошибку «заголовки уже отправлены», проблемы с с RSS-лентами или другие неполадки, попробуйте деактивировать или удалить этот плагин.

Все оказалось очень просто в конце написанного мной плагина стояли пробелы, убрал их и все пропало.

**Comment by PrudnikovMihail** [comment]
Сайт http://test.krasotinka.ru/
Плагин http://pastebin.com/YtdNxuGr
Шаблон https://yadi.sk/d/dii8IZPNjdPzG

**Comment by yumashev** [comment]
какая то беда с цветами http://test.krasotinka.ru/films/
зачем что то менять без причины? тем более если не умеешь подбирать цвета?

**Comment by PrudnikovMihail** [comment]
Цвета исправил.

И вопрос по плагину моему. Я конечно только начинаю и много не знаю, но та блок с html не красиво выглядит. Сейчас нашел вроде бы решение использовать функцию ob_start(). Зкажите это будет правильно использовать ее.

**Comment by yumashev** [comment]
Да, я ob_start в таких случаях использую.

**Comment by yumashev** [comment]
напиши тут свою почту

**Comment by PrudnikovMihail** [comment]
webmaster.inet@yandex.ru

**Comment by PrudnikovMihail** [comment]
webmaster.inet@yandex.ru

**Comment by PrudnikovMihail** [comment]
Вроде бы смог победить пункт #29 https://github.com/systemo-biz/casepress/issues/29
