### ISSUE TITLE
п. 2.2., вопрос №1

### ISSUE THREAD

**Issue by ghost** [wpcraft-ru/test#76]
Какими способами (без правки шаблона) можно определить, что текущая страница предназначена для вывода списка фильмов?

**Comment by yumashev** [comment]
условным тегом http://wp-kama.ru/id_89/uslovnyie-tegi-v-wordpress-i-vse-chto-s-nimi-svyazano.html
список тут http://wp-kama.ru/function-tag/uslovnyie-tegi - выбери подходящий

**Comment by fw72** [comment]
Пробовал 	if( has_tag( 'page_of_films_list' ) )   - не получилось.
Хотя get_the_tag_list() выдаёт правильный список.

Сделал [b]то же[/b] через категории - получилось.

**Comment by yumashev** [comment]
has_tag - проверяет термин
тебе надо проверить список фильмов. список фильмов это тип поста, а не термин.

**Comment by fw72** [comment]
А-а-а, понятно.
Через категории-то можно оставить, раз работает?

Хотя тип новый тип поста - films_list_post - сегодня удалил, т. к. думал, что не понадобится.

**Comment by yumashev** [comment]
хз, посмотрим по результату.
слабо понимаю как можно указать условие показа данных у списка постов по категории

**Comment by fw72** [comment]
В моём способе решения проверяется, относится ли страница к категории "список фильмов", и если да, то должен вывестись список всех film с подробностями.

**Comment by yumashev** [comment]
с точки зрения кода ты прав.
с точки зрения архитектуры, что это еще за категория список фильмов? от куда она взялась? как тебе удалось такое придумать?

категория фильма - это Ужасы, Фантастика, Комедия и т д. Не может быть категории фильма "список фильмов".

**Comment by fw72** [comment]
А, понятно. Верну тогда тип films_list_post.

Просто перебирал варианты реализации. И остановился на том, что указано выше. Может быть потому, что в <u>первую</u> очередь думал "с точки зрения кода".

**Comment by fw72** [comment]
Чтоб было понятнее, как я до такого додумался, приведу анекдот (может и не на 100% в тему). 

Едут по Австралии биолог, физик и математик и видят: на лугу пасется черная овца.
Биолог: "Смотрите, в Австралии обитают черные овцы!".
Физик: "Нет, в Австралии обитает как минимум одна черная овца."
Математик: "Нет, господа. В Австралии обитает как минимум одна овца, которая как минимум с одной
