### ISSUE TITLE
п. 2.2., вопрос №2

### ISSUE THREAD

**Issue by ghost** [wpcraft-ru/test#77]
<s>Как без лишнего кода (foreach и т. п.) получить список custom posts (в данном случае тип записи - "film")?</s>

**Comment by yumashev** [comment]
хз. надо точнее вопрос задать. че нужно сделать?

**Comment by fw72** [comment]
Правильно ли будет такой вариант:

в моей функции function films_list_inside_of_plugin($content) цикл через get_posts,
и в новой функции function display_film_data($myCurrentPostId) уже вывод?

**Comment by fw72** [comment]
Работает.

Осталось оформить вывод деталей по фильмам (пока только содержимое выводится) с исп. boostrpat и потом попробовать без новой функции обойтись.

**Comment by fw72** [comment]
Пробовал по инструкции http://wp-kama.ru/function/the_permalink выводить заголовок в цикле, но
the_permalink(), get_the_ID() не срабатывало.

Но в этом же цикле данные через $post-> правильные.

Чтобы по инструкции работало, нужно как-то по-другому цикл сделать, не через foreach?


Сейчас код такой:

			$args = array( 'posts_per_page' => -1, 'post_type' => 'film' );
			$lastposts = get_posts( $args );
			foreach( $lastposts as $post ){ setup_postdata($post);
				
				echo '<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>';
				echo $post->ID.'<br/>'; //testing only
				display_film_data($post->ID);
			}
			wp_reset_postdata();

**Comment by fw72** [comment]
Если foreach приемлем, то собираюсь доделать через $post->ID (в отдельной функции).

**Comment by fw72** [comment]
Попробовал через WP_Query - работает the_title() и т. п.

**Comment by fw72** [comment]
Пиздец, провозился с созданием заголовков (чтоб в виде ссылки и с кириллицей, без знаков процентов). Только сейчас получилось через get_the_title() и get_permalink().

А вот это

echo 'title_via_func: <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>';

работало не должным образом.

Уже собрался возвращаться к get_posts и foreach.
