### ISSUE TITLE
Отчет

### ISSUE THREAD

**Issue by latish86** [wpcraft-ru/test#78]
Ссылка на сайт: http://systemo.ijun.ru/
Ссылка на плагин: http://pastebin.com/MUpL8SFM
Убитый экран шаблона: http://i74.fastpic.ru/big/2015/1029/2e/d60d7e9bc89c8080045b491cfe8d912e.jpg

Возникла проблема с шорт-кодом. Точнее не с ним, а с отображением страницы. Не получается загрузить нужный шаблон страницы. Всегда подключается content.php.

**Comment by yumashev** [comment]
1. не понятно как работает главная
2. список 5 фильмов - нужен просто список
3. вопрос задан плохо, не понятно что ты хочешь и что сделано. при такой постановке вопросы мало шансов что кто либо поможет.
