### ISSUE TITLE
Задание выполнено.

### ISSUE THREAD

**Issue by sermustang** [wpcraft-ru/test#80]
1. Сайт - http://trotsenko-example.adr.com.ua/wordpress/
2. Плагин - http://pastebin.com/u01kCXCM
   Используемая в плагине часть шаблона - http://pastebin.com/KWJ7Brwj
3. Код шаблона страницы фильма - https://monosnap.com/file/COJJ562mgzqjbqYaOIeU9n6PrtqC1u#

**Comment by yumashev** [comment]
Вывод фильмов с ошибкой. При 5 фильмах этого не видно. Будет 50 фильмов и все встанет.
Список фильмов выводится без шаблона. Вообще шаблоны трогать не надо. Список просто сам выводится если открыть нужный адрес с кодом типа поста фильма.

**Comment by yumashev** [comment]
включи пермалинки, а то без них смотрится плохенько

**Comment by yumashev** [comment]
не понятно зачем вывод списка фильмов сделан через хук. дичайшее усложнее. все на много проще. + нарушение требования 2.4.2 - не внимательное изучение требований задания.

**Comment by sermustang** [comment]
Переделал. Сделал вывод списка фильмов проще, без шаблонов. Раньше не знал, что для нового типа записи создается отдельный архив с таким же названием. Также прочитал про ob_start.
Переделанный плагин - http://pastebin.com/Vx6LKRhy
Пермалинки поменял.
Не понял ваш последний пост. Вы имели ввиду список последних 5-ти фильмов? Я его сделал через шоркод в fuctions.php - https://monosnap.com/file/Xggq9vKKFnD55yhLPSHMy6oZPbw3LF#

**Comment by yumashev** [comment]
ок, напиши тут email

**Comment by sermustang** [comment]
sergeyt89@mail.ru
