### ISSUE TITLE
Кажется все готово 

### ISSUE THREAD

**Issue by alshchetinin** [wpcraft-ru/test#82]
Привет. Вроде бы сделал все правильно, вопросов было много, так как php первый раз увидел можно сказать) Но есть гугл, плюс смотрел работы других учасников, и делал все задания по ним. 

Ссылка на сайт - http://wpsystemo.alexsat0.bget.ru/

Ссылка на плагин - http://pastebin.com/L7aHF5xc

Скриншот шаблона - http://take.ms/L8UKL

**Comment by yumashev** [comment]
напомни адрес почты

**Comment by alshchetinin** [comment]
alexsander.qw@gmail.com
