### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by ophyros** [wpcraft-ru/test#84]
Проверьте, пожалуйста, вроде все сделал.
Сайт - http://ophyros.esy.es/
Плагин - http://pastebin.com/k5fu2RUJ
Шаблон - http://take.ms/hSO3A

**Comment by yumashev** [comment]
Не плохо. Даже придраться не к чему )
Напиши тут свою почту

**Comment by ophyros** [comment]
ophyros@gmail.com
