### ISSUE TITLE
На проверку тестового задания

### ISSUE THREAD

**Issue by inoirman** [wpcraft-ru/test#85]
Выношу на строгий суд.
1. http://kino.sm-dev.ru/
2. http://pastebin.com/DAfvLDPP
3. http://take.ms/q71Sw

**Comment by yumashev** [comment]
по коду все ок. не понятно зачем описание данных в метки упаковано.

черкни email

**Comment by inoirman** [comment]
А я и сам так до конца не понял, зачем я их начал в метки упаковывать ... Тот самый случай, когда вовремя остановился и не стал "не стоит излишне куролесить со стилями". Не дизайнер я ...

noir.ik@gmail.com
