### ISSUE TITLE
Проверьте, пожалуйста

### ISSUE THREAD

**Issue by promotorov** [wpcraft-ru/test#99]
Привет:)
Сайт: http://taskkk.esy.es/
Плагин: http://pastebin.com/KuPrJmiW
Шаблон: 
![bandicam 2016-04-10 19-28-04-860](https://cloud.githubusercontent.com/assets/18381389/14411502/b81f93ec-ff52-11e5-950e-90d451e43018.jpg)

**Comment by yumashev** [comment]
Какая то жесть с типографикой. Как тебе это удалось?
Стили внутри DOM-дерева - это очень плохо. Без веской причины нельзя пихать стили в HTML.

**Comment by promotorov** [comment]
Исправил: 
Сайт: http://taskkk.esy.es/
Плагин: http://pastebin.com/2LnxDzdn

**Comment by promotorov** [comment]
Исправил:
https://github.com/systemo-biz/test/issues/99#issuecomment-211160554

18 апреля 2016 г., 5:29 пользователь Anatoly Yumashev <
notifications@github.com> написал:

**Comment by promotorov** [comment]
Вы как-то прореагируете?

18 апреля 2016 г., 14:59 пользователь Vlad Promotorov <
vladpromotorov@gmail.com> написал:

**Comment by yumashev** [comment]
Все ок. Напомни почту.

**Comment by promotorov** [comment]
vladpromotorov@gmail.com

**Comment by promotorov** [comment]
vladpromotorov@gmail.com
18 мая 2016 г. 13:39 пользователь "Vlad Promotorov" <
vladpromotorov@gmail.com> написал:

> vladpromotorov@gmail.com
>
